name: Bazel Tests

permissions: read-all

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  bazel_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Run tests
        id: run_tests
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: bazel test //bazel/python/tests:stock_data_test --build_event_binary_file=bep.bin --nobuild_event_binary_file_path_conversion
        continue-on-error: true

      - name: Process test results
        # Run this step even if the test step ahead fails
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: "https://api.trunk-staging.io"
        with:
          bazel-bep-path: bep.bin
          use-bazel-target-for-codeowners: true
          org-slug: trunk-staging-org
          cli-version: 0.12.11-beta.1
          public-repo-id: NNSvcFXb
          # Pass the test outcome for quarantining support
          previous-step-outcome: ${{ steps.run_tests.outcome }}
