name: Retryable Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  retry_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: trunk install
        uses: trunk-io/trunk-action/install@v1
        with:
          tools: gh

      - name: download artifact (when retrying)
        if: ${{ fromJSON(github.run_attempt) > 1}}
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          pr: ${{github.event.pull_request.number}}
          name: retry-data
          workflow_conclusion: ""
          if_no_artifact_found: error

      - name: test
        id: run_tests
        shell: bash
        run: behave --junit-directory=python/results --junit python/behave
        continue-on-error: true

      - name: Process test results
        # Run this step even if the test step ahead fails
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: ${{ vars.TRUNK_API_ENDPOINT }}
          TRUNK_PUBLIC_REPO_ID_ENV: NNSvcFXb
        with:
          # Path to your test results.
          junit-paths: "**/python/results/*-behave.xml"
          # Provide your Trunk organization slug.
          org-slug: ${{ vars.ORG_SLUG }}
          cli-version: 0.12.11-beta.1
          # Pass the test outcome for quarantining support
          previous-step-outcome: ${{ steps.run_tests.outcome }}

      - name: Upload JUnit XML artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: retry-behave-junit-results
          path: "**/python/results/*-behave.xml"
          retention-days: 7

      - name: upload artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: retry-data
          path: "**/python/behave/retry.data"
          retention-days: 5

      - name: trigger job re-run
        if: ${{ failure() && steps.run_tests.conclusion == 'failure' && fromJSON(github.run_attempt) < 5}}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run rerun.yaml -F run_id=${{ github.run_id }}
