name: Ruby Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  ruby_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true

      # this is the recommended way to run rspec tests using the trunk rspec plugin
      - name: Run rspec tests (with trunk rspec plugin)
        id: rspec_trunk_tests
        if: ${{ always() }}
        working-directory: ruby/trunk_rspec
        env:
          TRUNK_PUBLIC_API_ADDRESS: "https://api.trunk-staging.io"
          TRUNK_ORG_URL_SLUG: trunk-staging-org
        run: bundle exec rspec
        continue-on-error: true

      - name: Run rspec tests
        id: rspec_tests
        if: ${{ always() }}
        run: bundle exec rspec ruby/rspec --format RspecJunitFormatter --out rspec_test.xml
        continue-on-error: true

      - name: Process rspec results
        # Run this step even if the test step ahead fails
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: "https://api.trunk-staging.io"
        with:
          # Path to your test results.
          junit-paths: "**/rspec_test.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk-staging-org
          cli-version: 0.12.11-beta.1
          public-repo-id: NNSvcFXb
          # Pass the test outcome for quarantining support
          previous-step-outcome: ${{ steps.rspec_tests.outcome }}
          test-collection-id: KtSNo9rY

      - name: Run minitest tests
        id: minitest_tests
        if: ${{ always() }}
        run: bundle exec ruby ruby/minitest/mixer.rb
        continue-on-error: true

      - name: Process minitest results
        # Run this step even if the test step ahead fails
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: "https://api.trunk-staging.io"
        with:
          # Path to your test results.
          junit-paths: "**/ruby/minitest/results/*.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk-staging-org
          cli-version: 0.12.11-beta.1
          public-repo-id: NNSvcFXb
          # Pass the test outcome for quarantining support
          previous-step-outcome: ${{ steps.minitest_tests.outcome }}
          test-collection-id: KtSNo9rY

      - name: Upload JUnit XML artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ruby-junit-results
          path: |
            **/rspec_test.xml
            **/ruby/minitest/results/*.xml
          retention-days: 7
