name: Rust Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  rust_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: cargo build -q --all --manifest-path=./rust/Cargo.toml

      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Install trunk-analytics-cli
        run: bash get-trunk-cli

      - name: Run rust tests
        id: run_tests
        if: ${{ always() }}
        run: cargo nextest run --profile=ci --manifest-path=./rust/Cargo.toml
        continue-on-error: true
        
      - name: Run rust tests and upload results
        env:
          TRUNK_PUBLIC_API_ADDRESS: ${{ vars.TRUNK_API_ENDPOINT }}
        run: |
          ./trunk-analytics-cli test \
            --org-url-slug ${{ vars.ORG_SLUG }} \
            --public-repo-id NNSvcFXb \
            --junit-paths "rust/**/nextest/ci/*junit.xml" \
            -- cargo nextest run --profile=ci --manifest-path=./rust/Cargo.toml

      - name: Upload JUnit XML artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: rust-junit-results
          path: rust/**/nextest/ci/*junit.xml
          retention-days: 7

